name: my_senger
description: "This is a simple a chat application using firebase."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.0
  intl: ^0.20.2
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  http: ^1.6.0
  file_picker: ^10.3.10
  cached_network_image: ^3.4.1
  pinput: ^6.0.1
  shared_preferences: ^2.5.4


  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  firebase_app_check: ^0.4.1+4
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^20.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true